# Generated by Django 5.2.7 on 2025-12-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_frame_count_session_last_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d2rresult',
            name='phase_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
