# Generated by Django 5.2.7 on 2026-09-15 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_studentnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('local_processing', 'Procesamiento local'), ('derived_persistence', 'Persistencia de datos derivados'), ('research', 'Uso en investigación')], max_length=32)),
                ('action', models.CharField(choices=[('grant', 'Otorgar'), ('decline', 'Rechazar'), ('revoke', 'Revocar')], max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='web', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['participant', 'purpose', 'created_at'], name='api_consent_partici_2591c6_idx')],
            },
        ),
    ]
