# Generated by Django 5.2.7 on 2026-09-15 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_pr03_pr07'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('aggregation_version', models.CharField(max_length=64)),
                ('features', models.JSONField(default=dict)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InferredState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('no_observable', 'No observable'), ('unknown', 'Unknown'), ('attentive', 'Attentive'), ('distracted', 'Distracted')], max_length=32)),
                ('probabilities', models.JSONField(default=dict)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('model_reference', models.CharField(blank=True, max_length=128)),
                ('inference_version', models.CharField(max_length=64)),
                ('inferred_at', models.DateTimeField()),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inferred_states', to='api.observationwindow')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporal_session', to='api.session')),
                ('d2r_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporal_session', to='api.d2rsession')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='api.inferredstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='api.inferredstate')),
                ('temporal_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='api.temporalsession')),
            ],
        ),
        migrations.AddField(
            model_name='observationwindow',
            name='temporal_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='api.temporalsession'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('kind', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('values', models.JSONField(default=dict)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temporal_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='api.temporalsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('suppressed', 'Suppressed'), ('presented', 'Presented')], default='proposed', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('policy_version', models.CharField(max_length=64)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggering_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='api.inferredstate')),
                ('temporal_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='api.temporalsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='inferredstate',
            index=models.Index(fields=['window', 'inferred_at'], name='api_inferre_window__808899_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferredstate',
            constraint=models.CheckConstraint(condition=models.Q(('uncertainty__isnull', True), models.Q(('uncertainty__gte', 0.0), ('uncertainty__lte', 1.0)), _connector='OR'), name='inferred_state_uncertainty_unit_range'),
        ),
        migrations.AddIndex(
            model_name='temporalsession',
            index=models.Index(fields=['participant', 'started_at'], name='api_tempora_partici_116b2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='temporalsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course_session__isnull', False), ('d2r_session__isnull', True)), models.Q(('course_session__isnull', True), ('d2r_session__isnull', False)), _connector='OR'), name='temporal_session_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='temporalsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='temporal_session_valid_range'),
        ),
        migrations.AddIndex(
            model_name='statetransition',
            index=models.Index(fields=['temporal_session', 'occurred_at'], name='api_statetr_tempora_c2abf0_idx'),
        ),
        migrations.AddIndex(
            model_name='observationwindow',
            index=models.Index(fields=['temporal_session', 'started_at'], name='api_observa_tempora_262d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationwindow',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='observation_window_positive_duration'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['temporal_session', 'captured_at'], name='api_observa_tempora_ca5932_idx'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(('received_at__gte', models.F('captured_at'))), name='observation_received_after_capture'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(('processed_at__isnull', True), ('processed_at__gte', models.F('received_at')), _connector='OR'), name='observation_processed_after_received'),
        ),
        migrations.AddIndex(
            model_name='interventionrecord',
            index=models.Index(fields=['temporal_session', 'occurred_at'], name='api_interve_tempora_8a30d2_idx'),
        ),
    ]
