# Generated by Django 5.2.7 on 2026-09-15 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_observationwindow_inferredstate_temporalsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('artifact_uri', models.CharField(max_length=512)),
                ('algorithm', models.CharField(max_length=128)),
                ('feature_contract', models.CharField(max_length=64)),
                ('dataset_reference', models.CharField(max_length=128)),
                ('code_revision', models.CharField(max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('evaluation', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('validated', 'Validated'), ('active', 'Active'), ('retired', 'Retired'), ('blocked', 'Blocked')], default='candidate', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'status'], name='api_modelar_name_1769b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_model_name_version'), models.UniqueConstraint(fields=('artifact_sha256',), name='uniq_model_artifact_sha256'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('name',), name='uniq_active_model_per_name')],
            },
        ),
        migrations.AddField(
            model_name='inferredstate',
            name='model_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inferences', to='api.modelartifact'),
        ),
    ]
