# Generated by Django 5.2.7 on 2026-09-15 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_modelartifact_inferredstate_model_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentarySelfReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('prompt_version', models.CharField(max_length=64)),
                ('response', models.CharField(choices=[('focused', 'Focused'), ('distracted', 'Distracted'), ('unsure', 'Unsure'), ('omitted', 'Omitted')], max_length=16)),
                ('requested_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_kind', models.CharField(blank=True, max_length=32)),
                ('resource_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='momentary_self_reports', to=settings.AUTH_USER_MODEL)),
                ('temporal_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reports', to='api.temporalsession')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_reports', to='api.observationwindow')),
            ],
            options={
                'indexes': [models.Index(fields=['temporal_session', 'requested_at'], name='api_momenta_tempora_6ec222_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('responded_at__isnull', True), ('responded_at__gte', models.F('requested_at')), _connector='OR'), name='self_report_response_after_request')],
            },
        ),
    ]
