# Generated by Django 5.2.7 on 2026-09-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_momentaryselfreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(choices=[('resource_open', 'Resource open'), ('pause', 'Pause'), ('resume', 'Resume'), ('navigation', 'Navigation'), ('activity', 'Activity'), ('micro_assessment', 'Micro assessment')], max_length=32)),
                ('resource_kind', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('activity', 'Activity')], max_length=16)),
                ('resource_reference', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('consent_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temporal_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='api.temporalsession')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_events', to='api.observationwindow')),
            ],
            options={
                'indexes': [models.Index(fields=['temporal_session', 'occurred_at'], name='api_learnin_tempora_9684f3_idx')],
            },
        ),
    ]
