# Generated by Django 5.2.7 on 2026-09-15 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_learninginteractionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.UUIDField(unique=True)),
                ('manual_version', models.CharField(max_length=64)),
                ('sample_stratum', models.CharField(max_length=64)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observer_assignments', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observer_assignments', to='api.observationwindow')),
            ],
        ),
        migrations.CreateModel(
            name='ObserverAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('attentive', 'Attentive'), ('distracted', 'Distracted'), ('no_observable', 'No observable'), ('uncertain', 'Uncertain')], max_length=32)),
                ('confidence', models.FloatField()),
                ('notes_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='annotation', to='api.observerassignment')),
            ],
        ),
        migrations.AddIndex(
            model_name='observerassignment',
            index=models.Index(fields=['observer', 'assigned_at'], name='api_observe_observe_fff5cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='observerassignment',
            constraint=models.UniqueConstraint(fields=('window', 'observer'), name='uniq_observer_per_window'),
        ),
        migrations.AddConstraint(
            model_name='observerannotation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='observer_annotation_confidence_range'),
        ),
    ]
