# Generated by Django 5.2.7 on 2026-09-15 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_observerassignment_observerannotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicVaultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_pseudonym', models.UUIDField(unique=True)),
                ('encrypted_payload', models.BinaryField()),
                ('consent_version', models.CharField(max_length=64)),
                ('retention_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vault_demographic_record',
            },
        ),
        migrations.CreateModel(
            name='DemographicVaultAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('outcome', models.CharField(max_length=16)),
                ('reason_code', models.CharField(max_length=64)),
                ('pseudonym_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demographic_vault_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_demographic_audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPseudonymMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_pseudonym', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='research_pseudonym_map', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_research_pseudonym_map',
            },
        ),
    ]
