# Generated by Django 5.2.7 on 2026-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_demographicvaultrecord_demographicvaultaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(unique=True)),
                ('operation', models.CharField(max_length=32)),
                ('subject_digest', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('counts', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retention_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
