# Generated by Django 5.2 for the pilot calibration and observer separation.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_quizattempt_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Estudiante"),
                    ("teacher", "Profesor"),
                    ("admin", "Administrador"),
                    ("researcher", "Investigador"),
                    ("observer", "Observador"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ResearchCalibration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("ready", "Ready")], default="ready", max_length=16)),
                ("calibration_version", models.CharField(max_length=64)),
                ("execution_profile", models.CharField(max_length=16)),
                ("sample_counts", models.JSONField(default=dict)),
                ("quality", models.JSONField(default=dict)),
                ("duration_ms", models.PositiveIntegerField()),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_calibrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_calibration",
                        to="api.session",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="researchcalibration",
            index=models.Index(fields=["participant", "completed_at"], name="api_rescal_partici_664a62_idx"),
        ),
    ]
