"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
STRICT_EVENT_IDENTITY = os.environ.get('STRICT_EVENT_IDENTITY', 'True').strip().lower() == 'true'
EVENT_SESSION_MAX_AGE_MINUTES = int(os.environ.get('EVENT_SESSION_MAX_AGE_MINUTES', '480'))
D2R_ENABLED = os.environ.get('D2R_ENABLED', 'False').strip().lower() == 'true'
TEMPORAL_SCHEMA_V2 = os.environ.get('TEMPORAL_SCHEMA_V2', 'False').strip().lower() == 'true'
MODEL_REGISTRY = os.environ.get('MODEL_REGISTRY', 'False').strip().lower() == 'true'
EVENT_CONTRACT_V2 = os.environ.get('EVENT_CONTRACT_V2', 'False').strip().lower() == 'true'
MOMENTARY_SELF_REPORT = os.environ.get('MOMENTARY_SELF_REPORT', 'False').strip().lower() == 'true'
LEARNING_INTERACTION_EVENTS = os.environ.get('LEARNING_INTERACTION_EVENTS', 'False').strip().lower() == 'true'
OBSERVER_ANNOTATION = os.environ.get('OBSERVER_ANNOTATION', 'False').strip().lower() == 'true'
REDIS_ENABLED = os.environ.get('REDIS_ENABLED', 'False').strip().lower() == 'true'
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0').strip()
REDIS_NAMESPACE = os.environ.get('REDIS_NAMESPACE', 'visionclass:v1').strip()
REDIS_DEFAULT_TTL_SECONDS = int(os.environ.get('REDIS_DEFAULT_TTL_SECONDS', '3600'))
DISTRIBUTED_STATE = os.environ.get('DISTRIBUTED_STATE', 'False').strip().lower() == 'true'
STREAM_PIPELINE = os.environ.get('STREAM_PIPELINE', 'False').strip().lower() == 'true'
STREAM_MAX_RETRIES = int(os.environ.get('STREAM_MAX_RETRIES', '3'))
DEMOGRAPHIC_VAULT = os.environ.get('DEMOGRAPHIC_VAULT', 'False').strip().lower() == 'true'
DEMOGRAPHIC_VAULT_KEY = os.environ.get('DEMOGRAPHIC_VAULT_KEY', '').strip()
RETENTION_JOBS = os.environ.get('RETENTION_JOBS', 'False').strip().lower() == 'true'
NORMALIZED_FEATURES_V1 = os.environ.get('NORMALIZED_FEATURES_V1', 'False').strip().lower() == 'true'
QUALITY_GATE_V1 = os.environ.get('QUALITY_GATE_V1', 'False').strip().lower() == 'true'
RETENTION_AUDIT_SECRET = os.environ.get('RETENTION_AUDIT_SECRET', '').strip()
OBSERVATION_RETENTION_DAYS = int(os.environ.get('OBSERVATION_RETENTION_DAYS', '30'))
STATE_RETENTION_DAYS = int(os.environ.get('STATE_RETENTION_DAYS', '90'))
TELEMETRY_RETENTION_DAYS = int(os.environ.get('TELEMETRY_RETENTION_DAYS', '30'))
DEVICE_BUDGET_TELEMETRY = os.environ.get('DEVICE_BUDGET_TELEMETRY', 'False').strip().lower() == 'true'
DEVICE_BUDGET_TELEMETRY_TTL_HOURS = int(os.environ.get('DEVICE_BUDGET_TELEMETRY_TTL_HOURS', '24'))
DEVICE_BUDGET_TELEMETRY_MIN_INTERVAL_SECONDS = int(
    os.environ.get('DEVICE_BUDGET_TELEMETRY_MIN_INTERVAL_SECONDS', '30')
)
ML_SERVICE_IDENTITY = os.environ.get('ML_SERVICE_IDENTITY', 'True').strip().lower() == 'true'
ML_SERVICE_NAME = os.environ.get('ML_SERVICE_NAME', 'visionclass-ml').strip()
ML_SERVICE_TOKEN = os.environ.get('ML_SERVICE_TOKEN', '').strip()
ML_SERVICE_PREVIOUS_TOKEN = os.environ.get('ML_SERVICE_PREVIOUS_TOKEN', '').strip()
ML_SERVICE_SCOPES = tuple(
    scope.strip()
    for scope in os.environ.get('ML_SERVICE_SCOPES', 'events:write').split(',')
    if scope.strip()
)
ML_EVENT_MAX_BYTES = int(os.environ.get('ML_EVENT_MAX_BYTES', '16384'))
TEMPORAL_INFERENCE_API = os.environ.get('TEMPORAL_INFERENCE_API', 'False').strip().lower() == 'true'
TEMPORAL_INFERENCE_MAX_BYTES = int(os.environ.get('TEMPORAL_INFERENCE_MAX_BYTES', '16384'))

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'vision_system'),
        'USER': os.environ.get('DB_USER', 'vision_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '12345'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}
if os.environ.get("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.parse(
        os.environ["DATABASE_URL"],
        conn_max_age=600,
        ssl_require=not DEBUG,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'api.User'
SITE_ID = int(os.environ.get('SITE_ID', '1'))
CONSENT_V2_ENABLED = os.environ.get('CONSENT_V2_ENABLED', 'True') == 'True'
CONSENT_TEXT_APPROVED = os.environ.get('CONSENT_TEXT_APPROVED', 'False') == 'True'
CONSENT_CURRENT_VERSION = os.environ.get('CONSENT_CURRENT_VERSION', 'PENDING-ETHICS-APPROVAL')

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

cors_allow_all = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False") == "True"
CORS_ALLOW_ALL_ORIGINS = cors_allow_all
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Dev defaults for local testing
if DEBUG:
    local_origins = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    for origin in local_origins:
        if origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False") == "True"
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "False") == "True"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False") == "True"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.environ.get("ACCESS_TOKEN_MINUTES", "60"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.environ.get("REFRESH_TOKEN_DAYS", "7"))),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_USE_JWT = True

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = "api.adapters.VisionClassAccountAdapter"
SOCIALACCOUNT_ADAPTER = "api.adapters.VisionClassSocialAccountAdapter"

SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ALLOW_SIGNUPS = True

ACCOUNT_ALLOW_REGISTRATION = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": "",
        }
    }
}

GOOGLE_OAUTH_CALLBACK_URL = os.environ.get(
    "GOOGLE_OAUTH_CALLBACK_URL",
    "http://localhost:3000/login",
)

MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY", "")
MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN", "")
MAILGUN_BASE_URL = os.environ.get("MAILGUN_BASE_URL", "https://api.mailgun.net")
MAILGUN_FROM_EMAIL = os.environ.get("MAILGUN_FROM_EMAIL", "VisionClass <noreply@visionclass.local>")
